### ISSUE TITLE
Unable to use JetBrains Plugin with PyCharm 2026.2 EAP 7

### ISSUE THREAD

**Issue by AndrewUshakov** [cline/cline#11830]
### Cline Surface

JetBrains Plugin

### Cline Version

1.1.58, and/or 1.1.60-nightly.20260623.398

### Beta version

- [ ] I am using a beta version of Cline

### What happened?

Empty CLINE tool window instead of the welcome screem, Java excepption. Idea.log is below:

```
2026-06-25 02:46:46,246 [ 206987]   INFO - #c.i.u.j.JBCefApp - Using bundle path from: class com.intellij.jcef.frontend.PluggableCefNativeBundleProvider path:C:\Users\UshakovAY\AppData\Local\Programs\PyCharm 2\plugins\jcef-plugin\jcef
2026-06-25 02:46:51,619 [ 212360] SEVERE - #c.i.i.p.PluginManager - com/intellij/ui/jcef/JBCefApp
java.lang.NoClassDefFoundError: com/intellij/ui/jcef/JBCefApp
	at bot.cline.intellij.toolWindow.ClineBrowserPanel.<init>(ClineBrowserPanel.kt:20)
	at bot.cline.intellij.toolWindow.ClineToolWindowFactory.createToolWindowContent(ClineToolWindowFactory.kt:11)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:788)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:765)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:987)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:918)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:615)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl$default(ToolWindowManagerImpl.kt:582)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1877)
	at com.intellij.openapi.wm.impl.SquareAnActionButton.setSelected(SquareStripeButton.kt:391)
	at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:62)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:283)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:262)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks$lambda$1$0(ActionManagerImpl.kt:623)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.ThrowableComputableToLambda.invoke(coroutines.kt:351)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.runWriteIntentReadAction(NestedLocksThreadingSupport.kt:710)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:1218)
	at com.intellij.openapi.application.WriteIntentReadAction.computeThrowable(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks$lambda$1(ActionManagerImpl.kt:812)
	at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:307)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:620)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:262)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:578)
	at java.desktop/java.awt.Component.processEvent(Component.java:6396)
	at java.desktop/java.awt.Container.processEvent(Container.java:2260)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2318)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4836)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4932)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4562)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4503)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2304)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2713)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4836)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:734)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:711)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:731)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:637)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:568)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0$0$0$0(IdeEventQueue.kt:388)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:941)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0$0$0(IdeEventQueue.kt:387)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$0(IdeEventQueue.kt:1122)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1122)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0(IdeEventQueue.kt:382)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:422)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.ClassNotFoundException: com.intellij.ui.jcef.JBCefApp PluginClassLoader(plugin=PluginMainDescriptor(name=Cline, id=bot.cline, version=1.1.58, isBundled=false, path=~\AppData\Roaming\JetBrains\PyCharm2026.2\plugins\cline), packagePrefix=null, state=active, parents=ContentModuleDescriptor(id=intellij.platform.vcs.log.graph) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.xml.emmet) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.vcs.log) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.smRunner, loadingRule=REQUIRED) <- PluginMainDescriptor(name=Test Runner, id=intellij.testRunner.plugin, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\plugins\platform-testRunner-plugin), ContentModuleDescriptor(id=intellij.platform.structureView) <- PluginMainDescriptor(name=Structure View, id=intellij.structureView.plugin, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\plugins\platform-structureView-plugin), ContentModuleDescriptor(id=intellij.platform.todo) <- PluginMainDescriptor(name=TODO Comments, id=intellij.todo.plugin, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\plugins\platform-todo-plugin), ContentModuleDescriptor(id=intellij.platform.bookmarks, loadingRule=REQUIRED) <- PluginMainDescriptor(name=Bookmarks Manager, id=intellij.bookmarks.plugin, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\plugins\platform-bookmarks-plugin), ContentModuleDescriptor(id=intellij.platform.vcs.dvcs) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.structuralSearch) <- PluginMainDescriptor(name=Structural Search, id=intellij.structuralSearch.plugin, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\plugins\platform-structuralSearch-plugin), ContentModuleDescriptor(id=intellij.relaxng) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.vcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.vcs.log.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.vcs.dvcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.spellchecker) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.spellchecker.xml) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.scriptDebugger.protocolReaderRuntime) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.scriptDebugger.backend) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.scriptDebugger.ui) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.tasks) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.tasks.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools.auth.base) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools.auth) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8117.23, isBundled=true, path=~\AppData\Local\Programs\PyCharm 2\lib), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 55 more
```

### Steps to reproduce

1. Install PyCharm 2026.2 EAP 7
2. Install CLINE
3. Optionally change Boot Java Runtime to 25.03+9-508.16-jcef (without this step error will be the same)
4. Restart PyCharm, enable CLINE tool window.
5. Try to open - java exception occurs, see log above. CLINE tool window remains empty.

All is Ok with PyCharm 2026.1.3

PyCharm Issue has been created and immediately closed:  https://youtrack.jetbrains.com/issue/PY-90530/Unable-to-use-CLINE-extension-in-2026.2-EAP7

### Provider/Model

Error occurs before CLINE configuration...

### IDE / CLI Diagnostics

PyCharm 2026.2 EAP
Build #PY-262.8117.23, built on June 18, 2026
Source revision: f0c4c63511770
Licensed to PyCharm EAP user: Andrey Ushakov
Expiration date: July 18, 2026
Runtime version: 25.0.3+9-b508.4 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 11.0
Exception reporter ID: 161225155839271-5296-48f4-b584-743693b7b446
JCEF version: 144.0.15-262-b37
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 2048MiB
Cores: 16
Registry:
  projectView.hide.dot.idea=false
  documentation.show.toolbar=true
  ide.experimental.ui=true
  llm.rules.refresh.interval=10
  llm.selector.config.refresh.interval=10
  llm.chat.agent.codex.install.codex.version=0.106.0
  llm.chat.agent.codex.install.acp.server.version=0.0.27
Non-Bundled Plugins:
  bot.cline (1.1.60-nightly.20260623.398)
  Docker (262.8117.26)
  org.jetbrains.dbt (262.8117.19)
  com.intellij.ideolog (262.8117.14)
  com.intellij.ml.llm (262.8117.23)
  org.jetbrains.security.package-checker (262.8117.19)
  com.intellij.lang.qml (262.8117.14)
  com.intellij.qt (262.8117.14)
  hg4idea (262.8117.14)
  PerforceDirectPlugin (262.8117.14)
  Subversion (262.8117.46)

### System Information

Windows 11, x64.

**Comment by gbrennon** [comment]
v4 release was published!
can u update to last released version to verify if that was fixed?

**Comment by AndrewUshakov** [comment]
@gbrennon: I am sorry, but how?  I can only update JetBrains plugin to the latest version 1.1.60-nightly.20260625.400. Will be core service also updated to v4 with this procedure?

**Comment by gbrennon** [comment]
im sorry, what was an auto reply/ jetbrains is not updated yet only vscode extension

**Comment by AndrewUshakov** [comment]
@gbrennon: plugin and acp-agent updated, including core-service, nothing changed. ACP agent generates error in 2026.1.3 and 2026.2 EAP if use it in AI Assistant, so EAP is fully unusable ([PY-90583](https://youtrack.jetbrains.com/issue/PY-90583) CLINE ACP-agent can't be used in AI Assistant):
```
ACP process exited unexpectedly. Exit code: -4058. Process output:
npm warn Unknown env config "min-release-age". This will stop working in the next major version of npm.

npm error code ENOENT

npm error syscall open
npm error path C:\Users\UshakovAY\AppData\Local\JetBrains\PyCharm2026.1\acp-agents\.runtimes\node\24.13.0\npm-cache\_npx\4bac6aec23e7b2ba\package.json

npm error errno -4058

npm error enoent Could not read package.json: Error: ENOENT: no such file or directory, open 'C:\Users\UshakovAY\AppData\Local\JetBrains\PyCharm2026.1\acp-agents\.runtimes\node\24.13.0\npm-cache\_npx\4bac6aec23e7b2ba\package.json'

npm error enoent This is related to npm not being able to find a file.
npm error enoent

npm error A complete log of this run can be found in: C:\Users\UshakovAY\AppData\Local\JetBrains\PyCharm2026.1\acp-agents\.runtimes\node\24.13.0\npm-cache\_logs\2026-06-26T05_51_00_715Z-debug-0.log
```

**Comment by vgylys** [comment]
I'm also having similar problel with IntelliJ 2026.2. Cline plugin version 1.1.60

Stack trace from the intellij logs:

`2026-07-17 12:36:16,921 [ 346359] SEVERE - #c.i.o.a.i.ExceptionsKt - Unhandled exception in EDT
com.intellij.openapi.diagnostic.UnhandledException: com/intellij/ui/jcef/JBCefApp
	at com.intellij.openapi.application.impl.ExceptionsKt.processUnhandledException(exceptions.kt:56)
	at com.intellij.platform.ide.bootstrap.StartupErrorReporter.processException(StartupErrorReporter.java:349)
	at com.intellij.ide.IdeEventQueue.processException(IdeEventQueue.kt:476)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:738)
	at com.intellij.ide.IdeEventQueue.dispatchMouseEvent(IdeEventQueue.kt:637)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:568)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0$0$0$0(IdeEventQueue.kt:388)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:941)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0$0$0(IdeEventQueue.kt:387)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$0(IdeEventQueue.kt:1122)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:114)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1122)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0(IdeEventQueue.kt:382)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:422)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoClassDefFoundError: com/intellij/ui/jcef/JBCefApp
	at bot.cline.intellij.toolWindow.ClineBrowserPanel.<init>(ClineBrowserPanel.kt:20)
	at bot.cline.intellij.toolWindow.ClineToolWindowFactory.createToolWindowContent(ClineToolWindowFactory.kt:11)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:788)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:765)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:987)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:918)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:615)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activateToolWindow$intellij_platform_ide_impl$default(ToolWindowManagerImpl.kt:582)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.activated$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1877)
	at com.intellij.openapi.wm.impl.SquareAnActionButton.setSelected(SquareStripeButton.kt:391)
	at com.intellij.openapi.actionSystem.ToggleAction.actionPerformed(ToggleAction.java:62)
	at com.intellij.openapi.actionSystem.impl.ActionButton.actionPerformed(ActionButton.java:283)
	at com.intellij.openapi.actionSystem.impl.ActionButton.lambda$performAction$0(ActionButton.java:262)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks$lambda$1$0(ActionManagerImpl.kt:623)
	at com.intellij.openapi.application.WriteIntentReadAction.lambda$run$0(WriteIntentReadAction.java:24)
	at com.intellij.openapi.application.ThrowableComputableToLambda.invoke(coroutines.kt:351)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.runWriteIntentReadAction(NestedLocksThreadingSupport.kt:710)
	at com.intellij.openapi.application.impl.ApplicationImpl.runWriteIntentReadAction(ApplicationImpl.java:1218)
	at com.intellij.openapi.application.WriteIntentReadAction.computeThrowable(WriteIntentReadAction.java:55)
	at com.intellij.openapi.application.WriteIntentReadAction.run(WriteIntentReadAction.java:23)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks$lambda$1(ActionManagerImpl.kt:812)
	at com.intellij.concurrency.ThreadContext.installThreadContext(threadContext.kt:307)
	at com.intellij.openapi.actionSystem.impl.ActionManagerImpl.performWithActionCallbacks(ActionManagerImpl.kt:620)
	at com.intellij.openapi.actionSystem.impl.ActionButton.performAction(ActionButton.java:262)
	at com.intellij.openapi.actionSystem.impl.ActionButton.processMouseEvent(ActionButton.java:578)
	at java.desktop/java.awt.Component.processEvent(Component.java:6396)
	at java.desktop/java.awt.Container.processEvent(Container.java:2260)
	at java.desktop/java.awt.Component.dispatchEventImpl(Component.java:5008)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2318)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4836)
	at java.desktop/java.awt.LightweightDispatcher.retargetMouseEvent(Container.java:4932)
	at java.desktop/java.awt.LightweightDispatcher.processMouseEvent(Container.java:4562)
	at java.desktop/java.awt.LightweightDispatcher.dispatchEvent(Container.java:4503)
	at java.desktop/java.awt.Container.dispatchEventImpl(Container.java:2304)
	at java.desktop/java.awt.Window.dispatchEventImpl(Window.java:2713)
	at java.desktop/java.awt.Component.dispatchEvent(Component.java:4836)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:734)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:711)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:731)
	... 16 more
Caused by: java.lang.ClassNotFoundException: com.intellij.ui.jcef.JBCefApp PluginClassLoader(plugin=PluginMainDescriptor(name=Cline, id=bot.cline, version=1.1.60, isBundled=false, path=~\AppData\Roaming\JetBrains\IntelliJIdea2026.2\plugins\cline), packagePrefix=null, state=active, parents=ContentModuleDescriptor(id=intellij.libraries.groovy, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=Groovy Scripting, id=com.intellij.groovy.scripting, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\plugins\groovy-scripting), ContentModuleDescriptor(id=intellij.platform.vcs.log.graph) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.xml.emmet) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.ssh.core, loadingRule=REQUIRED) <- PluginMainDescriptor(name=SSH, id=intellij.ssh.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\plugins\platform-ssh-plugin), ContentModuleDescriptor(id=intellij.platform.ssh, loadingRule=REQUIRED) <- PluginMainDescriptor(name=SSH, id=intellij.ssh.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\plugins\platform-ssh-plugin), ContentModuleDescriptor(id=intellij.platform.ssh.attach) <- PluginMainDescriptor(name=SSH, id=intellij.ssh.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\plugins\platform-ssh-plugin), ContentModuleDescriptor(id=intellij.platform.vcs.log) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.smRunner, loadingRule=REQUIRED) <- PluginMainDescriptor(name=Test Runner, id=intellij.testRunner.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\plugins\platform-testRunner-plugin), ContentModuleDescriptor(id=intellij.platform.structureView) <- PluginMainDescriptor(name=Structure View, id=intellij.structureView.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\plugins\platform-structureView-plugin), ContentModuleDescriptor(id=intellij.platform.todo) <- PluginMainDescriptor(name=TODO Comments, id=intellij.todo.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\plugins\platform-todo-plugin), ContentModuleDescriptor(id=intellij.platform.bookmarks, loadingRule=REQUIRED) <- PluginMainDescriptor(name=Bookmarks Manager, id=intellij.bookmarks.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\plugins\platform-bookmarks-plugin), ContentModuleDescriptor(id=intellij.platform.vcs.dvcs) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.structuralSearch) <- PluginMainDescriptor(name=Structural Search, id=intellij.structuralSearch.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\plugins\platform-structuralSearch-plugin), ContentModuleDescriptor(id=intellij.relaxng) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.vcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.vcs.log.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.vcs.dvcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.spellchecker) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.spellchecker.xml) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.scriptDebugger.protocolReaderRuntime) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.scriptDebugger.backend) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.scriptDebugger.ui) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.tasks) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.tasks.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools.auth.base) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools.auth) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\JetBrains\IntelliJ IDEA 2025.1\lib), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 55 more
2026-07-17 12:36:16,924 [ 346362] SEVERE - #c.i.o.a.i.ExceptionsKt - IntelliJ IDEA 2026.2  Build #IU-262.8665.258
2026-07-17 12:36:16,924 [ 346362] SEVERE - #c.i.o.a.i.ExceptionsKt - JDK: 25.0.3; VM: OpenJDK 64-Bit Server VM; Vendor: JetBrains s.r.o.
2026-07-17 12:36:16,924 [ 346362] SEVERE - #c.i.o.a.i.ExceptionsKt - OS: Windows 11
2026-07-17 12:36:16,924 [ 346362] SEVERE - #c.i.o.a.i.ExceptionsKt - Plugin to blame: Cline version: 1.1.60`

**Comment by AndrewUshakov** [comment]
@vgylys: Exactly the same error, which, from my point of view, occurs in JetBrains software during plugin initialization. Please, create issue in JetBrains  issue tracker. Mine was closed by formal reason. It will be also nice to get confirmation from CLINE developers, that it is an Idea/PyCharm issue.

**Comment by vgylys** [comment]
I can confirm that Cline plugin 1.1.63 works with IntelliJ IDEA 2026.2 Build #IU-262.8665.258

**Comment by mkondratek** [comment]
Thanks everyone for the reports and the patience, and @vgylys for confirming the fix — closing this as resolved.

What happened: starting with 2026.2, JetBrains moved JCEF out of the IDE platform into a separate bundled plugin (Web Browser (JCEF)). Cline versions up to 1.1.61 didn't declare a dependency on it, so on 2026.2 the IDE's plugin classloader had no path to the JCEF classes and the tool window crashed with `NoClassDefFoundError: com/intellij/ui/jcef/JBCefApp` — regardless of OS or which JetBrains IDE you used.

The fix: Cline 1.1.62 declares the dependency properly, and 1.1.63/1.1.64 are out as well — please update to the latest version. We've also marked the older versions as incompatible with 2026.2 on the Marketplace, so fresh installs can't run into this anymore. If you still see this on 1.1.62 or newer, please comment or open a new issue — that would be something new we'd want to look at.

@AndrewUshakov the ACP-agent error in AI Assistant is a separate problem (it lives in the JetBrains AI Assistant ↔ ACP integration, tracked on their side as PY-90583) — this fix won't change that. If the ACP path keeps failing with current versions, a dedicated issue with the exit-code output would help us figure out whether any part of it is ours.
