### ISSUE TITLE
Empty plugin window after IDEA update

### ISSUE THREAD

**Issue by lanmaster** [cline/cline#12361]
### Cline Surface

JetBrains Plugin

### Cline Version

1.1.60

### Beta version

- [ ] I am using a beta version of Cline

### What happened?

Today after IDEA update Cline plugin open with empty window.
IDEA version: 2026.2 (Build #IU-262.8665.258, built on July 15, 2026) 

### Steps to reproduce

1. Start IDEA
2. Open plugin window

<img width="1424" height="1210" alt="Image" src="https://github.com/user-attachments/assets/83c6bdf7-79d0-4849-8c2c-97355d3d56e7" />

### IDE / CLI Diagnostics

IntelliJ IDEA 2026.2
Build #IU-262.8665.258, built on July 15, 2026
Source revision: 9db502cc722e2
Runtime version: 25.0.3+9-b508.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.windows.WToolkit
Windows 10.0
Exception reporter ID: 18112414af1fead-8104-44e3-a675-b9d2bcb5b06f
JCEF version: 144.0.15-262-b37
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8200MiB
Cores: 32
Registry:
  trace.state.event.service.url=https://api.jetbrains.cloud/trace-status
Non-Bundled Plugins:
  com.intellij.aqua (262.8665.173)
  com.intellij.classic.ui (262.8665.173)
  bot.cline (1.1.60)
  org.jetbrains.debugger.streams (262.8665.173)
  ru.adelf.idea.dotenv (262.8665.270)
  org.jetbrains.completion.full.line (262.8665.258)
  zielu.gittoolbox (600.3.2+261)
  intellij.grid.loader.xls (262.8665.173)
  Batch Scripts Support (1.0.13)
  dev.turingcomplete.intellijdevelopertoolsplugins (9.0.0)
  com.github.setial (4.1.5)
  com.intellij.javaee.batch (262.8665.176)
  JavaScript (262.8665.258)
  intellij.jupyter (262.8665.270)
  com.intellij.jvm.dfa.analysis (262.8665.176)
  ai.kilocode.jetbrains (7.0.7)
  org.jetbrains.plugins.kotlin.jupyter (262.8665.176)
  org.mapstruct.intellij (1.9.1)
  MavenRunHelper (5.1.0-IJ2026.1)
  com.intellij.microservices.debugger (262.8665.176)
  com.intellij.ml.llm (262.8665.258)
  com.intellij.notebooks.core (262.8665.270)
  ee.carlrobert.chatgpt (3.8.2-261)
  com.intellij.reactivestreams (262.8665.176)
  io.github.aveenstra.run-anything (2.0)
  org.sonarlint.idea (12.5.0.84934)
  com.intellij.spring.batch (262.8665.176)
  com.intellij.spring.debugger (262.8665.176)
  com.intellij.spring.websocket (262.8665.176)
  com.intellij.tasks (262.8665.173)
  com.intellij.tasks.timeTracking (262.8665.173)
  fr.mathbou (2.1.0)
  org.jetbrains.plugins.github (262.8665.258)
  hg4idea (262.8665.173)
  PerforceDirectPlugin (262.8665.176)
  Subversion (262.8665.270)
  ZooCode (3.68.0)
Kotlin: 262.8665.258-IJ

### System Information

OS: Windows 10 x64
CPU: AMD Ryzen 9 7945HX
RAM: 64Gb
GPU: AMD Radeon(TM) 610M

**Comment by lanmaster** [comment]
I install latest nightly build (1.1.61-nightly.20260715.422) and have an error in window. Maybe it is related to initial question?

<img width="1278" height="1068" alt="Image" src="https://github.com/user-attachments/assets/8071db49-7e4a-41af-96fc-3a99f19af114" />

<img width="590" height="214" alt="Image" src="https://github.com/user-attachments/assets/892575b9-c764-4b7c-aceb-1d16202330b4" />

**Comment by jsalatas** [comment]
Same here in linux:

IntelliJ IDEA 2026.2
Build #IU-262.8665.258, built on July 15, 2026
Source revision: 9db502cc722e2
Runtime version: 25.0.3+9-b508.16 amd64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
Toolkit: sun.awt.wl.WLToolkit
Linux 6.17.0-35-generic
KDE neon User Edition; glibc: 2.39; desktop: KDE (plasmashell 6.7.2)
Exception reporter ID: 1004263b846bf46-c60d-4c18-bbcf-4fb228cf33f4
JCEF version: 144.0.15-262-b37
GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
Memory: 8192MiB
Cores: 20
Vulkan Rendering is ON:
  Presentation is ON
  NVIDIA RTX A2000 12GB (DISCRETE_GPU), caps=0xc0000006
  NVIDIA RTX A5000 (DISCRETE_GPU), caps=0xc0000006
  llvmpipe (LLVM 20.1.2, 256 bits) (CPU), caps=0xc0000006
Registry:
  ide.browser.jcef.contextMenu.devTools.enabled=true
  ide.browser.jcef.sandbox.enable=false
  ide.experimental.ui=true
  trace.state.event.service.url=https://api.jetbrains.cloud/trace-status
Non-Bundled Plugins:
  com.intellij.ml.llm (262.8665.258)
  com.intellij.notebooks.core (262.8665.270)
  ru.adelf.idea.dotenv (262.8665.270)
  org.jetbrains.junie (262.2144.50)
  com.intellij.ideolog (262.8665.173)
  Subversion (262.8665.270)
  PerforceDirectPlugin (262.8665.176)
  hg4idea (262.8665.173)
  intellij.jupyter (262.8665.270)
  bot.cline (1.1.60)
Kotlin: 262.8665.258-IJ
Current Desktop: KDE

**Comment by fabioflx** [comment]
Same here on my PhpStorm 2026.2 Build: #PS-262.8665.265 July 15, 2026 running on a Apple M5 with Apple macOS 26.5.2 (Tahoe) build 25F84.

**Comment by danielfgit** [comment]
The same issue, after update to 2026.2 Build #IU-262.8665.258, built on July 15, 2026 from 2026.1
The window window of Cline plugin is empty: “Nothing to show”.

I’ve tried enabling and disabling the plugin, but the result is the same.

2026-07-20 03:40:10,465 [  77343]   INFO - #c.i.o.a.ConfigImportHelper - Migrating plugin 'bot.cline' version: 1.1.60

idea.log

2026-07-20 08:02:10,614 [ 527135] SEVERE - #c.i.i.p.PluginManager - Plugin to blame: Cline version: 1.1.60
2026-07-20 08:02:10,620 [ 527141] SEVERE - #c.i.o.a.i.ExceptionsKt - Unhandled exception in EDT
com.intellij.openapi.diagnostic.UnhandledException: com/intellij/ui/jcef/JBCefApp

Caused by: java.lang.NoClassDefFoundError: com/intellij/ui/jcef/JBCefApp
    at bot.cline.intellij.toolWindow.ClineBrowserPanel.<init>(ClineBrowserPanel.kt:20)

When I made roolback to 2026.1.4, the plugin is working.

Environment:
OS: Windows (11.0)
JRE: 25.0.3+9-b508.16, amd64 (JetBrains s.r.o.)
JVM: 25.0.3+9-b508.16 (OpenJDK 64-Bit Server VM)
Cline Plugin: 1.1.60

**Comment by Hansz** [comment]
Same here:

IntelliJ IDEA 2026.2
Build #IU-262.8665.258, built on July 15, 2026
Source revision: 9db502cc722e2

**Comment by linyu003** [comment]
Cline Idea Plugin shows  only “Nothing to show” in it tool tab page.

Build #IU-262.8665.81, built on July 3, 2026

Licensed to IntelliJ IDEA EAP 
Expiration date: August 2, 2026

Runtime version: 25.0.3+9-b508.16 aarch64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.

JCEF version: 144.0.15-262-b37

**Comment by waoler** [comment]
Same issue here! I found this exception in the intellij idea.log file:

Environment: 

> IntelliJ IDEA 2026.2
> Build #IU-262.8665.258, built on July 15, 2026
> Source revision: 9db502cc722e2
> Runtime version: 25.0.3+9-b508.16 amd64
> VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
> Toolkit: sun.awt.windows.WToolkit
> Windows 11.0
> Exception reporter ID: 13042610624ab4b-0cf5-42ef-8e46-08e04b160ea5
> JCEF version: 144.0.15-262-b37
> GC: G1 Young Generation, G1 Concurrent GC, G1 Old Generation
> Memory: 4200MiB
> Cores: 16
> Registry:
>   ide.experimental.ui=true
>   trace.state.event.service.url=https://api.jetbrains.cloud/trace-status
>   vfs.windows.use.buffered.directory.stream=false
> Non-Bundled Plugins:
>   bot.cline (1.1.60)
>   org.jetbrains.debugger.streams (262.8665.173)
>   org.jetbrains.completion.full.line (262.8665.258)
>   com.github.deeepamin.gitlabciaid (2.0.0)
>   JavaScript (262.8665.258)
>   intellij.jupyter (262.8665.308)
>   org.jetbrains.kotlin (262.8665.258-IJ)
>   org.jetbrains.plugins.kotlin.jupyter (262.8665.176)
>   com.intellij.ml.llm (262.8665.258)
>   com.intellij.notebooks.core (262.8665.270)
>   org.sonarlint.idea (12.5.0.84934)
>   com.intellij.tasks (262.8665.173)
>   org.jetbrains.plugins.github (262.8665.258)
> Kotlin: 262.8665.258-IJ


`2026-07-21 11:42:02,895 [   3312] SEVERE - #c.i.o.w.i.ToolWindowManagerImpl - Cannot init toolwindow bot.cline.intellij.toolWindow.ClineToolWindowFactory@6fc62af0 [Plugin: bot.cline]
com.intellij.diagnostic.PluginException: Cannot init toolwindow bot.cline.intellij.toolWindow.ClineToolWindowFactory@6fc62af0 [Plugin: bot.cline]
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:286)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.access$registerToolWindows(ToolWindowSetInitializer.kt:1)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invokeSuspend(ToolWindowSetInitializer.kt:156)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invoke(ToolWindowSetInitializer.kt)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1$1.invoke(ToolWindowSetInitializer.kt)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndspatched(Undispatched.kt:67)
	at kotlinx.coroutines.intrinsics.UndispatchedKt.startUndispatchedOrReturn(Undispatched.kt:43)
	at kotlinx.coroutines.BuildersKt__Builders_commonKt.withContext(Builders.common.kt:165)
	at kotlinx.coroutines.BuildersKt.withContext(Unknown Source)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span(tracer.kt:62)
	at com.intellij.platform.diagnostic.telemetry.impl.TracerKt.span$default(tracer.kt:55)
	at com.intellij.toolWindow.ToolWindowSetInitializer$createAndLayoutToolWindows$entries$1.invokeSuspend(ToolWindowSetInitializer.kt:153)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:34)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:100)
	at com.intellij.openapi.application.impl.EdtCoroutineDispatcher.dispatch$run(EdtCoroutineDispatcher.kt:46)
	at com.intellij.openapi.application.TransactionGuardImpl$2.run(TransactionGuardImpl.java:231)
	at com.intellij.openapi.application.impl.NonBlockingFlushQueue.runNextEvent$lambda$1$1$0(NonBlockingFlushQueue.kt:329)
	at com.intellij.openapi.progress.impl.CoreProgressManager.computePrioritized(CoreProgressManager.java:941)
	at com.intellij.openapi.application.impl.NonBlockingFlushQueue.runNextEvent$lambda$1$1(NonBlockingFlushQueue.kt:328)
	at com.intellij.concurrency.ThreadContext.resetThreadContext(threadContext.kt:295)
	at com.intellij.openapi.application.impl.NonBlockingFlushQueue.runNextEvent$lambda$1(NonBlockingFlushQueue.kt:325)
	at com.intellij.platform.locking.impl.NestedLocksThreadingSupport.tryRunWriteIntentReadAction(NestedLocksThreadingSupport.kt:753)
	at com.intellij.openapi.application.impl.NonBlockingFlushQueue.runNextEvent(NonBlockingFlushQueue.kt:321)
	at com.intellij.openapi.application.impl.NonBlockingFlushQueue.flushNow(NonBlockingFlushQueue.kt:299)
	at com.intellij.openapi.application.impl.NonBlockingFlushQueue.FLUSH_NOW$lambda$0(NonBlockingFlushQueue.kt:158)
	at java.desktop/java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:323)
	at java.desktop/java.awt.EventQueue.dispatchEventImpl(EventQueue.java:732)
	at java.desktop/java.awt.EventQueue.dispatchEvent(EventQueue.java:711)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.kt:731)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.kt:584)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0$0$0(IdeEventQueue.kt:384)
	at com.intellij.ide.IdeEventQueueKt.performActivity$lambda$0(IdeEventQueue.kt:1122)
	at com.intellij.openapi.application.TransactionGuardImpl.performActivity(TransactionGuardImpl.java:106)
	at com.intellij.ide.IdeEventQueueKt.performActivity(IdeEventQueue.kt:1122)
	at com.intellij.ide.IdeEventQueue.dispatchEvent$lambda$0(IdeEventQueue.kt:382)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.kt:422)
	at java.desktop/java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:207)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:128)
	at java.desktop/java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:117)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:113)
	at java.desktop/java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:105)
	at java.desktop/java.awt.EventDispatchThread.run(EventDispatchThread.java:92)
Caused by: java.lang.NoClassDefFoundError: com/intellij/ui/jcef/JBCefApp
	at bot.cline.intellij.toolWindow.ClineBrowserPanel.<init>(ClineBrowserPanel.kt:20)
	at bot.cline.intellij.toolWindow.ClineToolWindowFactory.createToolWindowContent(ClineToolWindowFactory.kt:11)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.createContentIfNeeded(ToolWindowImpl.kt:788)
	at com.intellij.openapi.wm.impl.ToolWindowImpl.scheduleContentInitializationIfNeeded$intellij_platform_ide_impl(ToolWindowImpl.kt:765)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.doShowWindow(ToolWindowManagerImpl.kt:987)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl(ToolWindowManagerImpl.kt:918)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.showToolWindowImpl$default(ToolWindowManagerImpl.kt:899)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$lambda$6(ToolWindowManagerImpl.kt:1133)
	at com.intellij.openapi.wm.impl.ToolWindowManagerImpl.registerToolWindow$intellij_platform_ide_impl(ToolWindowManagerImpl.kt:1146)
	at com.intellij.toolWindow.ToolWindowSetInitializerKt.registerToolWindows(ToolWindowSetInitializer.kt:274)
	... 41 more
Caused by: java.lang.ClassNotFoundException: com.intellij.ui.jcef.JBCefApp PluginClassLoader(plugin=PluginMainDescriptor(name=Cline, id=bot.cline, version=1.1.60, isBundled=false, path=~\AppData\Roaming\JetBrains\IntelliJIdea2026.2\plugins\cline), packagePrefix=null, state=active, parents=ContentModuleDescriptor(id=intellij.libraries.groovy, loadingRule=EMBEDDED) <- PluginMainDescriptor(name=Groovy Scripting, id=com.intellij.groovy.scripting, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\plugins\groovy-scripting), ContentModuleDescriptor(id=intellij.platform.vcs.log.graph) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.xml.emmet) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.ssh.core, loadingRule=REQUIRED) <- PluginMainDescriptor(name=SSH, id=intellij.ssh.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\plugins\platform-ssh-plugin), ContentModuleDescriptor(id=intellij.platform.ssh, loadingRule=REQUIRED) <- PluginMainDescriptor(name=SSH, id=intellij.ssh.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\plugins\platform-ssh-plugin), ContentModuleDescriptor(id=intellij.platform.ssh.attach) <- PluginMainDescriptor(name=SSH, id=intellij.ssh.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\plugins\platform-ssh-plugin), ContentModuleDescriptor(id=intellij.platform.vcs.log) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.smRunner, loadingRule=REQUIRED) <- PluginMainDescriptor(name=Test Runner, id=intellij.testRunner.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\plugins\platform-testRunner-plugin), ContentModuleDescriptor(id=intellij.platform.structureView) <- PluginMainDescriptor(name=Structure View, id=intellij.structureView.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\plugins\platform-structureView-plugin), ContentModuleDescriptor(id=intellij.platform.todo) <- PluginMainDescriptor(name=TODO Comments, id=intellij.todo.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\plugins\platform-todo-plugin), ContentModuleDescriptor(id=intellij.platform.bookmarks, loadingRule=REQUIRED) <- PluginMainDescriptor(name=Bookmarks Manager, id=intellij.bookmarks.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\plugins\platform-bookmarks-plugin), ContentModuleDescriptor(id=intellij.platform.vcs.dvcs) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.structuralSearch) <- PluginMainDescriptor(name=Structural Search, id=intellij.structuralSearch.plugin, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\plugins\platform-structuralSearch-plugin), ContentModuleDescriptor(id=intellij.relaxng) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.vcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.vcs.log.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.vcs.dvcs.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.spellchecker) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.spellchecker.xml) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.scriptDebugger.protocolReaderRuntime) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.scriptDebugger.backend) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.scriptDebugger.ui) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.tasks) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.tasks.impl) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools.auth.base) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools.auth) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), ContentModuleDescriptor(id=intellij.platform.collaborationTools) <- PluginMainDescriptor(name=IDEA CORE, id=com.intellij, version=262.8665.258, isBundled=true, path=~\AppData\Local\Programs\IntelliJ IDEA 2026.1\lib), )
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.kt:154)
	at java.base/java.lang.ClassLoader.loadClass(ClassLoader.java:490)
	... 51 more`

**Comment by BarreiroT** [comment]
Hey! Thank you for the report. We made a fix, and it's gated by JetBrains' review. It should be updated soon. 

I will close this ticket in favor of #12435, and we will update there once it has been fixed.
